name : ascii-art

on : push

jobs :
  generate-ascii-art :
    runs-on : ubuntu-latest
    steps : 
      - name : checkout repo
        uses : actions/checkout@v7.0.1

      - name : list out contents
        run : ls -lah

      - name : run ascii script
        run : bash scripts/ascii-script.sh