name : ascii-art

on : push

jobs :
  generate-ascii-art :
    runs-on : ubuntu-latest
    steps : 
      - name : checkout repo
        uses : actions/checkout@v7.0.1

      - name : list out contents
        run : ls -lah

      - name : give the script execute access
        run : chmod +x scripts/ascii-scripts.sh

      - name : run ascii script
        run :  scripts/ascii-script.sh