name : contexts

on : push

jobs :
  explore-contexts : 
    runs-on : ubuntu-latest
    steps : 
      - name : display jobs context
        run : echo ${{toJson(job)}}
      
      - name : display steps context
        run : echo ${{toJson(steps)}}

      - name : display vars context
        run : echo ${{toJson(vars)}}
      
      - name : display secrets context
        run : echo ${{toJson(secrets)}}

      - name : display runner context
        run : echo ${{toJson(runner)}}