name : environment-variables

on : push

env :
  workflow-level-secret : workflow-level

jobs :
  job-one :
    runs-on : ubuntu-latest
    env :
      job-level-secret : job-level
    steps : 
      - name : step-one
        env : 
          step-level-secret : step-level
        run : echo $workflow-level-secret ${{env.job-level-secret}} $step-level-secret
      - name : step-two
        run : echo $workflow-level-secret $job-level-secret
    
  job-two : 
    runs-on : ubuntu-latest
    steps : 
      - name : step-one
        run : echo $workflow-level-secret