name : environment-variables

on : push

env :
  WORKFLOW_LEVEL_SECRET : workflow-level

jobs :
  job-one :
    runs-on : ubuntu-latest
    env :
      JOB_LEVEL_SECRET : job-level
    steps : 
      - name : step-one
        env : 
          STEP_LEVEL_SECRET : step-level
        run : echo $WORKFLOW_LEVEL_SECRET ${{env.JOB_LEVEL_SECRET}} $STEP-LEVEL-SECRET
      - name : step-two
        run : echo $WORKFLOW_LEVEL_SECRET $JOB_LEVEL_SECRET
    
  job-two : 
    runs-on : ubuntu-latest
    steps : 
      - name : step-one
        run : echo $WORKFLOW_LEVEL_SECRET