name : first workflow

on : push

jobs :
  first-job :
    runs-on : ubuntu-latest
    steps : 
    - name : use checkout
      uses : actions/checkout/@v7.0.1
    - name : welcome message
      run : echo "hello world!!"
    - name : list out all the files
      run : ls -lah
    - name : read readme
      run : cat README.md